### PR TITLE
Small fixes in visualizer + corrected players_files

### PR DESCRIPTION
**Pull request by dimatomp**

### CODE REVIEW

**Comment by valzevul** [comment]
Why are you using fnmatch instead of re.search in visualizer? And there are no reasons for fixes in tournament_systems/tournament_system_olympic.py@get_round_names, because your solution is more cumbersome (in my opinion).

p.S
I added you at consumers's list of this repository, so think of these suggestions and merge your commits on your own :).

**Comment by dimatomp** [comment]
> there are no reasons for fixes in tournament_systems/tournament_system_olympic.py@get_round_names

I've taken a look at the video we have shown in our presentation. The name of the final round in title screen was "1/16 final", name of semifinal was "final" and so on. This function worked incorrectly.

**Comment by dimatomp** [comment]
> Why are you using fnmatch instead of re.search in visualizer?

I don't see any reasons to use regexps in the filemask currently. That just makes usage of "create_video.py"
 more difficult to be understood.

**Comment by valzevul** [comment]
> This function worked incorrectly.

I have fixed it after presentation.

**Pull request merged**
